# Generated by Django 5.1.2 on 2024-10-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("CT", "Contract"),
                            ("IN", "Internship"),
                            ("FL", "Freelance"),
                        ],
                        max_length=2,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("education", models.TextField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="api.job",
                    ),
                ),
            ],
        ),
    ]
