# Generated by Django 5.1.2 on 2024-10-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_job_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_logo",
            field=models.ImageField(
                default="images/default-logo.png", upload_to="images/"
            ),
        ),
    ]
